import { ICategory } from '@/types/Covid';

const mapBoxToken = 'pk.eyJ1Ijoic2theW1hbnQiLCJhIjoiY2tiMGc2dGJhMDdzajJ4bWVtcnFrdHI5ZyJ9.JVI3u1rZALDoFrEjvcwZcg';

const coronaUrl = 'https://corona.lmao.ninja/v3/covid-19/countries';

const categories: ICategory[] = [
  { name: 'Cumulative Cases', id: 'AllCases', checked: true },
  { name: 'Today Cases', id: 'TodayCases', checked: false },
  { name: 'Incidence Rate', id: 'IncidenceRate', checked: false },
];

const layers: mapboxgl.AnyLayer[] = [
  {
    id: 'AllCases',
    source: 'AllCases',
    type: 'circle',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'circle-opacity': 1,
      'circle-stroke-width': ['interpolate', ['linear'], ['get', 'cases'], 1, 1, 100000, 1],
      'circle-radius': [
        'interpolate',
        ['linear'],
        ['get', 'cases'],
        1,
        2,
        10000,
        4,
        100000,
        5,
        250000,
        10,
        500000,
        15,
        2000000,
        20,
      ],
      'circle-color': [
        'interpolate',
        ['linear'],
        ['get', 'cases'],
        1,
        '#ffffb2',
        10000,
        '#fed976',
        50000,
        '#feb24c',
        100000,
        '#fd8d3c',
        250000,
        '#fc4e2a',
        500000,
        '#e31a1c',
        2000000,
        '#b10026',
      ],
    },
  },
  {
    id: 'TodayCases',
    source: 'TodayCases',
    layout: {
      visibility: 'none',
    },
    type: 'circle',
    paint: {
      'circle-opacity': 0.75,
      'circle-stroke-width': ['interpolate', ['linear'], ['get', 'cases'], 1, 1, 100000, 1],
      'circle-radius': [
        'interpolate',
        ['linear'],
        ['get', 'cases'],
        1,
        2,
        1000,
        4,
        2000,
        5,
        3000,
        10,
        4000,
        15,
        5000,
        20,
      ],
      'circle-color': [
        'interpolate',
        ['linear'],
        ['get', 'cases'],
        1,
        '#ebdb00',
        500,
        '#34cc15',
        1000,
        '#27a00f',
        2000,
        '#1d790b',
        5000,
        '#1ca800',
        7500,
        '#185a0b',
        10000,
        '#052900',
      ],
    },
  },
  {
    id: 'IncidenceRate',
    source: 'IncidenceRate',
    type: 'circle',
    layout: {
      visibility: 'none',
    },
    paint: {
      'circle-opacity': 0.75,
      'circle-stroke-width': ['interpolate', ['linear'], ['get', 'cases'], 1, 1, 100000, 1],
      'circle-radius': [
        'interpolate',
        ['linear'],
        ['get', 'cases'],
        1,
        2,
        1000,
        4,
        2000,
        5,
        3000,
        10,
        4000,
        15,
        5000,
        20,
      ],
      'circle-color': [
        'interpolate',
        ['linear'],
        ['get', 'cases'],
        1,
        '#44bef7',
        500,
        '#02a9f7',
        1000,
        '#006da0',
        2000,
        '#004363',
        5000,
        '#1205a3',
        7500,
        '#6605b6',
        10000,
        '#21013b',
      ],
    },
  },
];

export {
  mapBoxToken, coronaUrl, layers, categories,
};
